name: Build & Test

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Clean
        run: cargo clean
      - name: Build
        run: trunk build --release --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --all -- --check

  tailwind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install node packages
        run: npm ci
      - name: Build Tailwindcss
        run: npm run build
